name: Tests

on:
  push:
    branches:
        - 3.2.0_downgraded_deps
        - master
  pull_request:
    branches:
        - 3.2.0_downgraded_deps
        - master      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
